### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by Venefyxatu** [meta-it/odooselenium#4]
I'm missing some features I need at work, such as installing and configuring modules.
I'll gladly implement them as needed and need a ticket for commit messages and branch name; this is it.

**Comment by benoitbryon** [comment]
Welcome @Venefyxatu :)

I don't know if helps, but @n1b0r told me about [erppeek](http://erppeek.readthedocs.org/), which I used to setup Odoo server in test environment (Travis CI).
Have a look at [init_odoo.py](https://github.com/meta-it/odooselenium/blob/61df577b8276b2dc397659a329453f2e8648a232/init_odoo.py#L65-L74) script in this repository.

That said, this technique doesn't use selenium... i.e. it is good to automatically setup test environment, but not to check that user can actually configure Odoo using a web browser. Are you working on this "install/configure modules using browser" feature?

**Comment by Venefyxatu** [comment]
Thanks! This might be a good time to optimise my test cycle :-)

I'm indeed working on install/configure modules using browser and will make a pull request once I'm satisfied that it's stable enough.
