### ISSUE TITLE
Transfer pypi package to vauxoo

### ISSUE THREAD

**Issue by moylop260** [meta-it/odooselenium#7]
Hello,

We are developing a new package related to odoo-selenium

But we have the following error:
 - `400 The name 'odoo-selenium' is too similar to an existing project. See https://pypi.org/help/#project-name for more information.`

It looks like the project name https://pypi.org/project/odooselenium/ is detecting similar name

Could you transfer the ownership of pypi package to `vauxoo` pypi user if you are not planning to maintain this package anymore for new odoo versions, please?

Regards!

**Comment by metaminux** [comment]
Hi @moylop260 

This project is quite old... I'm trying to regain access to it or contact the other developers.

**Comment by metaminux** [comment]
Hi @moylop260 

This was quite long, but I regained access to my pypi account.

I just sent an invitation to the `vauxoo` pipy user to be an owner of the `odooselenium` package.

Regards,

**Comment by moylop260** [comment]
Hi @metaminux 

Thank you!

I appreciate it very much
